#!/usr/bin/env bash
set -e
cd "$(git rev-parse --show-toplevel)"
echo "Data e hora: $(TZ=Europe/London date "+%d/%m/%Y — %H:%M %Z")"
echo ""
echo "CONTEXTO PARA A PRÓXIMA CONVERSA"
echo ""
echo "Projeto: Repositório de Solicitadoria"
echo "Autor público: Paulo Silva (Pàjó)"
echo "URL: https://pajogusi.github.io/repositorio-solicitadoria/"
echo "Pasta local: ~/universidade-da-vida-direito"
echo ""
echo "ESTADO FECHADO"
echo "- 20 / 38 cadeiras concluídas"
echo "- 200 / 380 aulas concluídas"
echo "- Progresso global: 52,6%"
echo "- Última cadeira concluída: Direito Processual Civil II — 10 / 10"
echo "- Próxima cadeira correta: Direito Fiscal II"
echo ""
echo "SEQUÊNCIA CORRETA"
echo "21. Direito Fiscal II"
echo "22. Direito da Família e das Sucessões I"
echo "23. Direito das Sociedades"
echo "24. Princípios de Finanças"
echo "25. Direito Processual Civil III"
echo ""
echo "REGRAS"
echo "- Começar novas conversas com data e hora."
echo "- Confirmar sempre primeiro em que máquina estamos."
echo "- Se for paulo@paulo-755XDA: já está no portátil, não usar SSH para 192.168.1.195."
echo "- Se for dell@overdrive-core: está no Centro."
echo "- Criar uma aula de cada vez."
echo "- Atualizar apresentação da cadeira, cadeiras.html, index.html e paginas/mapa.html."
echo "- Não iniciar Direito Processual Civil III agora. A próxima é Direito Fiscal II."
echo ""
echo "VALIDAÇÃO ATUAL"
grep -n "Cadeiras concluídas\|Aulas concluídas" index.html || true
grep -n "Direito Processual Civil II\|Direito Fiscal II\|Direito Processual Civil III" cadeiras.html || true
echo ""
echo "GIT"
git status --short
